"""
Core Pydantic models for investment and financial analysis.

This module defines all data models used throughout the ROI calculator and
investment analysis components, with comprehensive validation and documentation.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field, field_validator, model_validator, ConfigDict
from enum import Enum
import numpy as np
import warnings

from .enums import CurrencyType, SensitivityParameter


class InvestmentInput(BaseModel):
    """
    Input model for investment analysis calculations.

    This model captures all necessary parameters for performing comprehensive
    investment analysis including ROI, NPV, IRR, and payback period calculations.

    Attributes:
        initial_investment: Total upfront capital investment required (must be positive)
        annual_revenue: Expected annual revenue generated by the investment
        annual_costs: Expected annual operating and maintenance costs
        discount_rate: Discount rate for NPV calculations (as decimal, e.g., 0.10 for 10%)
        project_lifetime: Expected lifetime of the project in years
        currency: Currency type for all monetary values
        tax_rate: Corporate tax rate (as decimal, e.g., 0.25 for 25%)
        salvage_value: Expected value at end of project lifetime
        inflation_rate: Expected annual inflation rate (as decimal)

    Example:
        >>> investment = InvestmentInput(
        ...     initial_investment=100000,
        ...     annual_revenue=25000,
        ...     annual_costs=5000,
        ...     discount_rate=0.10,
        ...     project_lifetime=25
        ... )
    """

    initial_investment: float = Field(
        ...,
        gt=0,
        description="Initial capital investment required",
        json_schema_extra={"examples": [100000, 500000, 1000000]},
    )

    annual_revenue: float = Field(
        ...,
        ge=0,
        description="Expected annual revenue from the investment",
        json_schema_extra={"examples": [25000, 50000, 100000]},
    )

    annual_costs: float = Field(
        ...,
        ge=0,
        description="Annual operating and maintenance costs",
        json_schema_extra={"examples": [5000, 10000, 20000]},
    )

    discount_rate: float = Field(
        default=0.10,
        ge=0.0,
        le=1.0,
        description="Discount rate for NPV calculations (as decimal)",
        json_schema_extra={"examples": [0.08, 0.10, 0.12]},
    )

    project_lifetime: int = Field(
        default=25,
        ge=1,
        le=50,
        description="Expected project lifetime in years",
        json_schema_extra={"examples": [20, 25, 30]},
    )

    currency: CurrencyType = Field(
        default=CurrencyType.USD, description="Currency for all monetary values"
    )

    tax_rate: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Corporate tax rate (as decimal)",
        json_schema_extra={"examples": [0.0, 0.21, 0.25, 0.30]},
    )

    salvage_value: float = Field(
        default=0.0,
        ge=0,
        description="Expected salvage value at end of project lifetime",
    )

    inflation_rate: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Expected annual inflation rate (as decimal)",
        json_schema_extra={"examples": [0.0, 0.02, 0.03]},
    )

    @field_validator("annual_costs")
    @classmethod
    def validate_costs_against_revenue(cls, v: float, info) -> float:
        """Ensure annual costs don't exceed annual revenue by too much."""
        if "annual_revenue" in info.data:
            annual_revenue = info.data["annual_revenue"]
            if v > annual_revenue * 1.5:
                warnings.warn(
                    f"Annual costs ({v}) seem unusually high compared to "
                    f"annual revenue ({annual_revenue}). Please verify inputs."
                )
        return v

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "initial_investment": 100000,
                "annual_revenue": 25000,
                "annual_costs": 5000,
                "discount_rate": 0.10,
                "project_lifetime": 25,
                "currency": "USD",
                "tax_rate": 0.21,
                "salvage_value": 10000,
                "inflation_rate": 0.02,
            }
        }
    )


class CashFlow(BaseModel):
    """
    Model representing cash flows over time.

    Attributes:
        year: Year number (0 for initial investment, 1+ for operating years)
        inflow: Cash inflow for this year
        outflow: Cash outflow for this year
        net_flow: Net cash flow (inflow - outflow)
        cumulative_flow: Cumulative cash flow up to this year
        discounted_flow: Discounted cash flow using specified discount rate
    """

    year: int = Field(..., ge=0, description="Year number")
    inflow: float = Field(..., description="Cash inflow for this year")
    outflow: float = Field(..., description="Cash outflow for this year")
    net_flow: float = Field(..., description="Net cash flow (inflow - outflow)")
    cumulative_flow: float = Field(..., description="Cumulative cash flow up to this year")
    discounted_flow: float = Field(
        ..., description="Discounted cash flow using specified discount rate"
    )

    @model_validator(mode="before")
    @classmethod
    def calculate_net_flow(cls, values):
        """Calculate net flow from inflow and outflow if not provided."""
        if isinstance(values, dict):
            if "net_flow" not in values:
                values["net_flow"] = values.get("inflow", 0) - values.get("outflow", 0)
        return values


class ROIResult(BaseModel):
    """
    Comprehensive result model for ROI and investment analysis.

    This model contains all key financial metrics calculated from the investment
    analysis, including ROI, NPV, IRR, and payback period.

    Attributes:
        roi_percentage: Return on Investment as a percentage
        net_present_value: Net Present Value of the investment
        internal_rate_of_return: Internal Rate of Return (IRR) as a percentage
        payback_period_years: Time to recover initial investment in years
        discounted_payback_period_years: Discounted payback period in years
        total_revenue: Total revenue over project lifetime
        total_costs: Total costs over project lifetime
        net_profit: Total net profit (revenue - costs - initial investment)
        profitability_index: NPV divided by initial investment
        annual_roi: Average annual ROI percentage
        cash_flows: Detailed cash flow breakdown by year
        currency: Currency for all monetary values

    Example:
        >>> result = ROIResult(
        ...     roi_percentage=150.5,
        ...     net_present_value=125000,
        ...     internal_rate_of_return=15.3,
        ...     payback_period_years=5.2
        ... )
    """

    roi_percentage: float = Field(
        ..., description="Return on Investment as a percentage"
    )

    net_present_value: float = Field(
        ..., description="Net Present Value of the investment"
    )

    internal_rate_of_return: Optional[float] = Field(
        None, description="Internal Rate of Return (IRR) as a percentage"
    )

    payback_period_years: Optional[float] = Field(
        None, ge=0, description="Simple payback period in years"
    )

    discounted_payback_period_years: Optional[float] = Field(
        None, ge=0, description="Discounted payback period in years"
    )

    total_revenue: float = Field(
        ..., description="Total revenue over project lifetime"
    )

    total_costs: float = Field(
        ..., description="Total costs over project lifetime"
    )

    net_profit: float = Field(
        ..., description="Total net profit after all costs"
    )

    profitability_index: float = Field(
        ..., description="NPV divided by initial investment"
    )

    annual_roi: float = Field(
        ..., description="Average annual ROI percentage"
    )

    cash_flows: List[CashFlow] = Field(
        default_factory=list, description="Detailed cash flow breakdown by year"
    )

    currency: CurrencyType = Field(
        default=CurrencyType.USD, description="Currency for all monetary values"
    )

    initial_investment: float = Field(
        ..., gt=0, description="Initial investment amount for reference"
    )

    discount_rate: float = Field(
        ..., ge=0, le=1, description="Discount rate used for calculations"
    )

    @property
    def is_profitable(self) -> bool:
        """Check if the investment is profitable (NPV > 0 and ROI > 0)."""
        return self.net_present_value > 0 and self.roi_percentage > 0

    @property
    def meets_hurdle_rate(self) -> bool:
        """Check if IRR exceeds the discount rate (hurdle rate)."""
        if self.internal_rate_of_return is None:
            return False
        return self.internal_rate_of_return > (self.discount_rate * 100)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "roi_percentage": 150.5,
                "net_present_value": 125000,
                "internal_rate_of_return": 15.3,
                "payback_period_years": 5.2,
                "discounted_payback_period_years": 6.8,
                "total_revenue": 625000,
                "total_costs": 125000,
                "net_profit": 400000,
                "profitability_index": 1.25,
                "annual_roi": 6.02,
                "currency": "USD",
                "initial_investment": 100000,
                "discount_rate": 0.10,
            }
        }
    )


class SensitivityInput(BaseModel):
    """
    Input model for sensitivity analysis.

    Defines which parameter to vary and the range of variation for sensitivity testing.

    Attributes:
        parameter: The parameter to vary in the analysis
        base_value: Base value of the parameter
        variation_range: Range of variation as percentages (e.g., [-20, -10, 0, 10, 20])
        variation_values: Explicit values to test (alternative to variation_range)

    Example:
        >>> sensitivity = SensitivityInput(
        ...     parameter=SensitivityParameter.DISCOUNT_RATE,
        ...     base_value=0.10,
        ...     variation_range=[-20, -10, 0, 10, 20]
        ... )
    """

    parameter: SensitivityParameter = Field(
        ..., description="The parameter to vary in the analysis"
    )

    base_value: float = Field(..., description="Base value of the parameter")

    variation_range: Optional[List[float]] = Field(
        None,
        description="Range of variation as percentages (e.g., [-20, -10, 0, 10, 20])",
        json_schema_extra={"examples": [[-20, -10, 0, 10, 20], [-30, -15, 0, 15, 30]]},
    )

    variation_values: Optional[List[float]] = Field(
        None,
        description="Explicit values to test (alternative to variation_range)",
    )

    @model_validator(mode="after")
    def validate_variation_inputs(self) -> "SensitivityInput":
        """Ensure either variation_range or variation_values is provided."""
        if self.variation_range is None and self.variation_values is None:
            raise ValueError(
                "Either variation_range or variation_values must be provided"
            )
        if self.variation_range is not None and self.variation_values is not None:
            raise ValueError(
                "Provide either variation_range or variation_values, not both"
            )
        return self

    def get_test_values(self) -> List[float]:
        """
        Get the list of values to test in sensitivity analysis.

        Returns:
            List of parameter values to test

        Raises:
            ValueError: If neither variation_range nor variation_values is set
        """
        if self.variation_values is not None:
            return self.variation_values

        if self.variation_range is not None:
            return [
                self.base_value * (1 + pct / 100) for pct in self.variation_range
            ]

        raise ValueError("No variation values configured")


class SensitivityResult(BaseModel):
    """
    Result model for a single sensitivity analysis data point.

    Attributes:
        parameter: The parameter that was varied
        parameter_value: The specific value tested
        roi_percentage: ROI for this parameter value
        net_present_value: NPV for this parameter value
        internal_rate_of_return: IRR for this parameter value
        payback_period_years: Payback period for this parameter value
    """

    parameter: SensitivityParameter = Field(..., description="The parameter that was varied")
    parameter_value: float = Field(..., description="The specific value tested")
    roi_percentage: float = Field(..., description="ROI for this parameter value")
    net_present_value: float = Field(..., description="NPV for this parameter value")
    internal_rate_of_return: Optional[float] = Field(
        None, description="IRR for this parameter value"
    )
    payback_period_years: Optional[float] = Field(
        None, description="Payback period for this parameter value"
    )


class SensitivityAnalysisResult(BaseModel):
    """
    Comprehensive result model for sensitivity analysis.

    Contains all sensitivity test results and statistical summaries.

    Attributes:
        parameter: The parameter that was varied
        base_case: Results for the base case (unvaried parameters)
        results: List of results for each parameter variation
        roi_range: Range of ROI values [min, max]
        npv_range: Range of NPV values [min, max]
        most_sensitive_to: Description of which variation had largest impact
        elasticity: Elasticity coefficient (% change in output / % change in input)
    """

    parameter: SensitivityParameter = Field(
        ..., description="The parameter that was varied"
    )

    base_case: ROIResult = Field(
        ..., description="Results for the base case (unvaried parameters)"
    )

    results: List[SensitivityResult] = Field(
        ..., description="List of results for each parameter variation"
    )

    roi_range: List[float] = Field(
        ..., min_length=2, max_length=2, description="Range of ROI values [min, max]"
    )

    npv_range: List[float] = Field(
        ..., min_length=2, max_length=2, description="Range of NPV values [min, max]"
    )

    most_sensitive_to: str = Field(
        ..., description="Description of which variation had largest impact"
    )

    elasticity: Optional[float] = Field(
        None, description="Elasticity coefficient (% change in output / % change in input)"
    )

    @property
    def roi_volatility(self) -> float:
        """Calculate ROI volatility (standard deviation of ROI across variations)."""
        roi_values = [r.roi_percentage for r in self.results]
        return float(np.std(roi_values))

    @property
    def npv_volatility(self) -> float:
        """Calculate NPV volatility (standard deviation of NPV across variations)."""
        npv_values = [r.net_present_value for r in self.results]
        return float(np.std(npv_values))

    model_config = ConfigDict(arbitrary_types_allowed=True)
